apiVersion: apps/v1
kind: Deployment
metadata:
  name: gifticon
  namespace: gifticon
  labels:
    app: gifticon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gifticon
  template:
    metadata:
      labels:
        app: gifticon
    spec:
      containers:
        - name: gifticon
          image: user05skccacr.azurecr.io/gifticon:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
